
name: 'AdventureWorks' # <-- Name of the project.
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  AdventureWorks:
    marts:
      +materialized: table
      +schema: marts
    staging:
      +materialized: view
      +schema: stg

seeds: # Carga dos dados no DW
  AdventureWorks: # Mesmo nome do modelo. Se mudar de 'AdventureWorks', alterar aqui
    sap_adventure_works:
      +schema: sap_adw